import type { Metadata, Viewport } from "next";
import { Roboto } from "next/font/google";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import { AppShell } from "@/components/app-shell";
import { PwaRegister } from "@/components/pwa-register";
import { ThemeRegistry } from "@/components/theme-registry";
import { ToastProvider } from "@/components/toast";
import { getSettings } from "@/lib/settings";
import { M3_DARK, M3_LIGHT } from "@/lib/m3-colors";
import startupImages from "@/lib/pwa-startup-images.json";
import "./globals.css";

// Roboto (Material's type face), self-hosted by next/font and handed to
// the MUI theme via the --font-roboto custom property.
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "YAFA — Yet Another Finance App",
  description: "Personal finance management",
  applicationName: "YAFA",
  manifest: "/manifest.webmanifest",
  // Installable on iOS/iPadOS via Share → Add to Home Screen. The
  // translucent status bar lets the app bar run edge to edge; the shell
  // pads for env(safe-area-inset-top). Splash images are generated by
  // scripts/generate-pwa-assets.mjs.
  appleWebApp: {
    capable: true,
    title: "YAFA",
    statusBarStyle: "black-translucent",
    startupImage: startupImages,
  },
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: M3_LIGHT.surface },
    { media: "(prefers-color-scheme: dark)", color: M3_DARK.surface },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSettings();
  const preference = settings.theme;

  return (
    <html lang="en" className={roboto.variable} suppressHydrationWarning>
      <body>
        {/* Sets data-mui-color-scheme before first paint so "system"
            and dark preferences never flash light. */}
        <InitColorSchemeScript defaultMode={preference} />
        <ThemeRegistry preference={preference}>
          <ToastProvider>
            <AppShell preference={preference}>{children}</AppShell>
          </ToastProvider>
        </ThemeRegistry>
        <PwaRegister />
      </body>
    </html>
  );
}
