import type { MetadataRoute } from "next";
import { M3_LIGHT } from "@/lib/m3-colors";

// Web app manifest — lets iOS/Android install YAFA to the home screen
// as a standalone app. Icons are generated by scripts/generate-pwa-assets.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: "YAFA — Yet Another Finance App",
    short_name: "YAFA",
    description: "Self-hosted personal finance and life admin.",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    display_override: ["standalone", "minimal-ui"],
    background_color: M3_LIGHT.surface,
    theme_color: M3_LIGHT.surface,
    lang: "en-GB",
    categories: ["finance", "productivity"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      { name: "Review", url: "/review", description: "Categorise new transactions" },
      { name: "Transactions", url: "/transactions" },
      { name: "Import a statement", url: "/imports" },
    ],
  };
}
